HTML_TAGS= [
    "a","abbr","address","area","article","aside","audio",
    "b","base","bdi","bdo","blockquote","body","br","button",
    "canvas","caption","cite","code","col","colgroup",
    "data","datalist","dd","del","details","dfn","dialog","div","dl","dt",
    "em","embed",
    "fieldset","figcaption","figure","footer","form",
    "h1","h2","h3","h4","h5","h6","head","header","hgroup","hr","html",
    "i","iframe","img","input","ins",
    "kbd","label","legend","li","link",
    "main","map","mark","menu","meta","meter",
    "nav","noscript",
    "object","ol","optgroup","option","output",
    "p","picture","pre","progress",
    "q",
    "rp","rt","ruby",
    "s","samp","script","section","select","slot","small","source","span","strong","style","sub","summary","sup",
    "table","tbody","td","template","textarea","tfoot","th","thead","time","title","tr","track",
    "u","ul",
    "var","video",
    "wbr",
  
    "_deprecated:center","_deprecated:font","_deprecated:big","_deprecated:tt",
    "_deprecated:acronym","_deprecated:applet","_deprecated:basefont",
    "_deprecated:bgsound","_deprecated:blink","_deprecated:marquee",
    "_deprecated:dir","_deprecated:isindex","_deprecated:keygen",
    "_deprecated:menuitem","_deprecated:multicol","_deprecated:nobr",
    "_deprecated:noembed","_deprecated:plaintext","_deprecated:rb",
    "_deprecated:spacer","_deprecated:strike","_deprecated:xmp"
  ]
  